services:
  - type: web
    name: collab-doc-editor-api
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: collab-doc-editor-db
          property: connectionString
      - key: JWT_PRIVATE_KEY
        sync: false
      - key: NODE_ENV
        value: production
